### ISSUE TITLE
Add make file for easy building

### ISSUE THREAD

**Issue by tsyesika** [tirea/fwew#1]
There is a `build.sh` file that allows for easy building but it'd be useful to have a make file, so it's easy for newcomers to the project to build it using the standard tools they might use to build other projects. This would also allow for cleanup and even installation.

**Comment by tirea** [comment]
I might actually tackle this real quick in a few minutes here if you don't have time.

**Comment by tsyesika** [comment]
Feel free :) If you've not done it by the time I'm planning to start it I'll re-claim it

**Comment by tirea** [comment]
I've made a Makefile and removed all shell scripts. :)
