### ISSUE TITLE
Number support

### ISSUE THREAD

**Issue by tsyesika** [tirea/fwew#2]
Fwew should be able to translate to and from base 8, the base the Na'vi use.

**Comment by tirea** [comment]
This is already on the roadmap. See TODO.md

**Comment by tirea** [comment]
What I plan to do with this eventually:

Concept of how it would work:

```
$ fwew -n 100
Decimal: 64
Na'vi: zam

$ fwew -n zam
Decimal: 64
Octal: 100

$ fwew -r -n 64
Octal: 100
Na'vi: zam
```

Or something similar.

**Comment by tirea** [comment]
Commit cc890ebfa366dcb0f007190f5b442c94d90802b5
just got damn close to nailing this.

**Comment by tirea** [comment]
It pretty much does this now.
